NPC: "&#123123Скупщик"
# Список предметов и цены (предметы писать капсом)
Items:
  Public:
    STONE: 1
    DIRT: 4
    COBBLESTONE: 2
    DIAMOND: 20
    LEATHER: 5
    ENDER_PEARL: 3
    EMERALD: 20
    REDSTONE_BLOCK: 80
    DIAMOND_BLOCK: 20
    COAL: 1
    PAPER: 1
    SPIDER_EYE: 20
Util:
  # Пермы, нужные для выполнения команд. User перм нужен для взаимодействия с НПС
  Perms:
    admin: richer.admin
    user: richer.user
  # Начальная часть всех команд плагина (/richer reload итп)
  Commands:
    all: richer
  Menu:
    #Название меню
    name: Скупщик
    #Список для добавления информации в книгу. %sender% - ник игрока
    'info':
    - "&#123123Игрок %sender%"
    #Строка о количестве оставшихся стаков в личных предложениях %amount% - их количество, %price% - цена,  %private_reset_time% - время ресета
    'private_info':
    - "&#123321Количество: %amount%, &#321122Цена: %price%"
    - "&#123321До обновления: %private_reset_time% минут"
    'local_info':
    - "&#123321Количество: %amount%, &#321122Цена: %price%"
    - "&#123321До обновления: %public_reset_time% минут"
    #Название предмета, отвечающего за донат обновление предложений
    update_name: "&#123123Обновление личных предложений за лаймы"
    #Расположение предмета отвечающего за обновление
    update_position: 0
    #Список для добавления информации в предмет отвечающий за донат обновление предложений
    'update_info':
    - "&#123123Нажмите для досрочного обновления"
    - "&#123123списка личных предложений."
    - "&#123123Цена: 100 лаймов"
    #Название информационного предмета
    info_name: "&#123123Информация"
    #Слот, в котором расположен информационный предмет
    info_position: 53
    #Порядок расстановки общих предложений
    'public_items':
     - 11
     - 12
     - 13
     - 14
     - 15
     - 21
     - 22
     - 23
     #Порядок расстановки приватных предложений
    'private_items':
     - 39
     - 40
     - 41
     #Порядок расстановки плейсхолдеров (зелёных панелей)
    'placeholder_items':
     - 30
     - 31
     - 32
  Messages:
    # Броадкаст об обновлении глобальных предложений
    Public_update: "&#808000Глобал &7был &0обновлён"
    # Броадкаст об обновлении локальных предложений
    Private_update: "&#808000Локал &7был &0обновлён"
# Через сколько должен происходить ресет (В СЕКУНДАХ!). Private - личные предложения, Public - общие.
Timings:
  Private: 180
  Public: 180